### ISSUE TITLE
.NET Standard/Core support

### ISSUE THREAD

**Issue by NickStrupat** [jamesfoster/DeepEqual#23]
Hi,

Do you have any plan any plan to implement .NET Standard or .NET Core support?

Thanks.

**Comment by Johlandabee** [comment]
I second that.

**Comment by nicolaiarocci** [comment]
A NetStandard 2.0 version of DeepEqual is available at [my fork](https://github.com/nicolaiarocci/DeepEqual). This is just as a proof of concept. If there enough interest and the project maintainer is willing to merge, I can refine it and submit a PR. 

Right now it is a separate project which uses linked files from the original one. Ideally, I would ditch the NET4 project in favor of the new one. This, however, would mean that the new version would not be usable by NET Frameworks older than 461. Since the library has been quite stable for a good while, I do not perceive this as a problem, but it is something worth considering.

**Comment by nicolaiarocci** [comment]
Went ahead and submitted PR #27.
