### ISSUE TITLE
Possible to ignore a property across all elements of an array?

### ISSUE THREAD

**Issue by JoshMcCullough** [jamesfoster/DeepEqual#25]
If I've missed some documentation which answers this, please let me know.

When doing a comparison, is it possible to ignore a property of an array element? E.g...

Instead of this:
```
actual.WithDeepEqual(expected)
    .IgnoreSourceProperty(o => o.People[0].Id)
    .IgnoreSourceProperty(o => o.People[1].Id)
    ...
    .IgnoreSourceProperty(o => o.People[n].Id)
    .Assert();
```

Do this:
```
actual.WithDeepEqual(expected)
    .IgnoreSourceArrayProperty(o => o.People, o => o.Id)
    .Assert();
```

That way, the comparison would ignore the `Id` property for each element in the `People` array on the source object.

**Comment by jamesfoster** [comment]
You can ignore properties on all instances a given type. e.g.

`.IgnoreProperty<Person>(x -> x.Id)`

should ignore all Id fields on all instances of `Person`.

**Comment by JoshMcCullough** [comment]
Thanks, it should work for this case. It would not work if you had a multiple collections of the same type on the object that was being verified, e.g. if in one collection you wanted to ignore `SomeField`, but in the other collection you wanted to verify it per usual.

**Comment by jamesfoster** [comment]
True. At the moment the only information you have to determine whether to ignore a property is the name and declaring type. In order to have different behaviours for the same type at different points in the object graph I think the easiest solution would be to expose the current breadcrumb (i.e. `"People[3].Id"`) but that would require you to parse that...

In all the cases I've seen, it's usually IDs and dates that you ignore and it's consistent between instances of the same type. I might consider adding this if there's a compelling use case.

Thanks
