### ISSUE TITLE
Sticking the differences into the Context object feels wrong

### ISSUE THREAD

**Issue by verybadcat** [jamesfoster/DeepEqual#33]
I notice that in the latest version, you are sticking Difference objects into the ComparisonContext. Tracking differences and having custom formatters could certainly make sense. But I think this is the wrong way to go about it. Logically, the Difference objects should be part of a Result object, not part of the ComparisonContext object. In other words, you would have a ResultModel object, or something like that. One of its fields could be a ComparisonResult -- pass, fail, or inconclusive. Another field might contain your differences.

In addition to making logical sense, this would eliminate the need to return two objects from your Compare methods.

**Comment by verybadcat** [comment]
Actually, looking at this more, it could be partly a naming issue. What if you rename ComparisonContext to ResultModel, or to ComparisonResultContext? But I still don't like the fact that you are returning two objects from your Compare methods. Is it possible to set things up so that the ComparisonResult enumeration value is one of the fields of the ResultModel (or whatever you end up calling it)? It's not immediately obvious; you might end up returning a smallish ResultModel from low-level comparisons, then combining them for higher-level comparisons.

**Comment by jamesfoster** [comment]
It's always been that way. Even in version 1 the differences were maintained in the "context" object. It was a mutable structure which contained the breadcrumb and the list of all differences seen so far. In version 2, I wanted it to take a more functional approach and make the context object immutable. I think it makes the code much neater and makes the intention of a Comparison clear.

We could create a custom return type with the 2 properties for the context and the result instead of using tuples. It does make the signature quite long but I don't mind it so much.
